services:
    app.command_handler.create_user_command_handler:
        class: App\Message\Command\CreateUserCommandHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.user_password_hasher'
            - '@event.bus'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    app.command_handler.verify_user_email_handler:
        class: App\Message\Command\VerifyUserEmailCommandHandler
        arguments:
            - '@symfonycasts.verify_email.helper'
            - '@doctrine.orm.default_entity_manager'
            - '@event.bus'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    app.command_handler.reset_user_password_command_handler:
        class: App\Message\Command\ResetUserPasswordCommandHandler
        tags:
            - { name: messenger.message_handler, bus: command.bus }