services:
    app.command_handler.create_user_command_handler:
        class: App\Message\Command\CreateUserCommandHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.user_password_hasher'
            - '@messenger.default_bus'
        tags:
            - { name: messenger.message_handler }