services:
    app.controller.action.login_action:
        class: App\Controller\Action\LoginAction
        arguments:
            - '@twig'
            - '@Symfony\Component\Security\Http\Authentication\AuthenticationUtils'
        tags:
            - { name: controller.service_arguments }

    app.controller.action.show_dashboard_action:
        class: App\Controller\Action\ShowDashboardAction
        arguments:
            - '@twig'
        tags:
            - { name: controller.service_arguments }

