services:
    app.event_handler.user_created_event_handler:
        class: App\Message\Event\UserCreatedEventHandler
        arguments:
            - '@mailer'
            - '@symfonycasts.verify_email.helper'
        tags:
            - { name: messenger.message_handler, bus: event.bus }