version: '3'

services:
    database:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
