App\Dto\UserDto:
    constraints:
        - App\Validator\UniqueDto:
              fields: email
              entityClass: App\Entity\User
              atPath: email
              message: user.email.unique
    properties:
        email:
            - Email: ~