App\Dto\UserDto:
    constraints:
        - App\Validator\UniqueDto:
              fields: email
              entityClass: App\Entity\User
              atPath: email
              message: user.email.unique
    properties:
        email:
            - Email: ~
              
App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - Email: ~

App\Dto\BuyCryptoCurrencyDto:
    properties:
        quantity:
            - GreaterThan: 0
        price:
            - LessThanOrEqual:
                propertyPath: userBalance

App\Dto\SellCryptoCurrencyDto:
    properties:
        quantity:
            - LessThanOrEqual:
                propertyPath: userQuantity
