login:
    path: /
    controller: App\Controller\Action\LoginUserAction

logout:
    path: /logout
    methods: GET

register:
    path: /register
    controller: App\Controller\Action\RegisterUserAction

verify_email:
    path: /verify-email
    controller: App\Controller\Action\VerifyUserEmailAction

dashboard:
    path: /dashboard
    controller: App\Controller\Action\ShowDashboardAction

reset_password_request:
    path: /reset-password-request
    controller: App\Controller\Action\ResetPasswordRequestAction

reset_password:
    path: /reset-password/{token}
    controller: App\Controller\Action\ResetPasswordAction
    defaults:
        token: null

buy_cryptocurrency:
    path: /buy/{symbol}
    controller: App\Controller\Action\CryptoCurrency\BuyCryptoCurrencyAction