login:
    path: /
    controller: app.controller.action.login_user_action

logout:
    path: /logout
    methods: GET

register:
    path: /register
    controller: app.controller.action.register_user_action

verify_email:
    path: /verify-email
    controller: app.controller.action.verify_user_email

dashboard:
    path: /dashboard
    controller: app.controller.action.show_dashboard_action

