#controllers:
#    resource: ../src/Controller/
#    type: attribute
#
login:
    path: /
    controller: app.controller.action.login_user_action

logout:
    path: /logout
    methods: GET

register:
    path: /register
    controller: app.controller.action.register_user_action

dashboard:
    path: /dashboard
    controller: app.controller.action.show_dashboard_action

