#controllers:
#    resource: ../src/Controller/
#    type: attribute
#
login:
    path: /
    controller: app.controller.action.login_action

dashboard:
    path: /dashboard
    controller: app.controller.action.show_dashboard_action