services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\Action\:
        resource: '../src/Controller/Action'
        tags: [ 'controller.service_arguments' ]

    Symfony\Component\Mailer\Mailer: ~